version: '3.8'
services:
  echo-service:
    build: .
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - type: bind
        source: ./app
        target: /app/
    environment:
      - FLASK_ENV=development
    command:
      wait-for-it --service database-service:5432 --timeout=0 --
      python /app/echo.py
  database-service:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
